### ISSUE TITLE
Storage method

### ISSUE THREAD

**Issue by CDFN** [workonfire/InventoryLogs#1]
Hey,
Great resource. However, I don't think saving to config.yml is good choice. This file is intended for configuration, not saving data. After few days logs will get very long which means two things:
1. Loading config.yml into RAM will take more and more space
2. File will get larger and larger, filtring it will get more difficult with time

I think you should consider using database, such as InfluxDB.

**Comment by workonfire** [comment]
> I don't think saving to config.yml is good choice. This file is intended for configuration, not saving data.

Yep, I know, I was thinking about it as well. I just didn't have enough time, though. Thanks for the suggestion, I'll do it the right way very soon.

I wouldn't consider switching to some other database system, since the original idea predicted, that the storage file would be opened **manually**, through a regular text editor.
From the user perspective, trying to configure an other database system would be time-consuming and ineffective, because there's no easy way to read the database contents, and will never be, since I didn't want this plugin to be that much customizable.
If I did, I'd implement much more features at once (for example the `/readlogs` command) and certainly take your suggestion into consideration. The plugin is very simple (and I think very easy to use), and I want it to stay that way.

> Loading config.yml into RAM will take more and more space
File will get larger and larger, filtring it will get more difficult with time

You're right. I missed that out. The user can delete the unnecessary file contents manually, though. But what do you think about implementing some kind of a log auto-purge system?

**Comment by CDFN** [comment]
AutoPurge isn't way to go imo, you don't want to delete something important by mistake. I'd just
a) create one file for one server enable
b) create one file for e.g. 3h

This way you don't have 20GB files and you can simply navigate to wanted file.

**Comment by workonfire** [comment]
Oh, that's even better! I'll go for it and implement it soon.
Thank you.
